DATAS SEGMENT
	arg1 DB 4 DUP(0)
	arg2 DB 4 DUP(0)
	B DB 4 DUP(0)
	A DB 4 DUP(0)
	CC DB 4 DUP(0)
	R DB 4 DUP(0)
	rr DB 4 DUP(0)
	t0 DB 4 DUP(0)
	t1 DB 4 DUP(0)
	t2 DB 4 DUP(0)
	t3 DB 4 DUP(0)
	t4 DB 4 DUP(0)
	t5 DB 4 DUP(0)
	t6 DB 4 DUP(0)
	t7 DB 4 DUP(0)
	t8 DB 4 DUP(0)
	t9 DB 4 DUP(0)
	t10 DB 4 DUP(0)
	t11 DB 4 DUP(0)
	t12 DB 4 DUP(0)
	t13 DB 4 DUP(0)
	t14 DB 4 DUP(0)
	t15 DB 4 DUP(0)
	t16 DB 4 DUP(0)
	t17 DB 4 DUP(0)
	t18 DB 4 DUP(0)
DATAS ENDS
STACKS SEGMENT
STACKS ENDS
CODES SEGMENT
	ASSUME CS : CODES, DS : DATAS, SS : STACKS
START :
	MOV AX, DATAS
	MOV DS, AX
	XOR DX, DX
	MOV WORD PTR A, 2
	MOV WORD PTR CC, 1
	MOV WORD PTR R, 3
	MOV WORD PTR rr, 1
	MOV AX, 2
	XOR DX, DX
	MOV BP,3
	MUL BP
	MOV BX, WORD PTR R
	ADD BX, WORD PTR rr
	XOR DX, DX
	MUL BX
	MOV AX, 2
	XOR DX, DX
	MOV BP,3
	MUL BP
	MOV BX, WORD PTR R
	ADD BX, WORD PTR rr
	XOR DX, DX
	MUL BX
	MOV BX, WORD PTR R
	SUB BX, WORD PTR rr
	XOR DX, DX
	DIV BX
	SUB AX,8
	PUSH DX
	PUSH AX
	PUSH SI
	MOV WORD PTR B, AX
	MOV SI, OFFSET B
	MOV DL, BYTE PTR[SI+1]
	ADD DL,'0'
	MOV AH,02H
	INT 21H
	MOV DL, BYTE PTR[SI]
	ADD DL,'0'
	MOV AH,02H
	INT 21H
	POP SI
	POP AX
	POP DX
	MOV BX, 2
	MOV WORD PTR B, AX
	MOV AX,BX
	XOR DX, DX
	MOV BP,3
	MUL BP
	MOV BX, WORD PTR B
	MOV WORD PTR t9, AX
	MOV AX,BX
	XOR DX, DX
	DIV WORD PTR CC
	MOV WORD PTR t10, AX
	MOV AX, WORD PTR t9
	ADD AX, WORD PTR t10
	MOV BX, 2
	MOV WORD PTR A, AX
	MOV AX,BX
	XOR DX, DX
	MOV BP,3
	MUL BP
	MOV BX, WORD PTR B
	MOV WORD PTR t12, AX
	MOV AX,BX
	XOR DX, DX
	DIV WORD PTR CC
	MOV WORD PTR t13, AX
	MOV AX, WORD PTR t12
	ADD AX, WORD PTR t13
	MOV BX, 2
	MOV WORD PTR B, AX
	MOV AX,BX
	XOR DX, DX
	MOV BP,3
	MUL BP
	MOV BX, WORD PTR B
	MOV WORD PTR t15, AX
	MOV AX,BX
	XOR DX, DX
	DIV WORD PTR CC
	MOV WORD PTR t16, AX
	MOV AX, WORD PTR t15
	ADD AX, WORD PTR t16
	SUB AX,7
	PUSH DX
	PUSH AX
	PUSH SI
	MOV WORD PTR CC, AX
	MOV SI, OFFSET CC
	MOV DL, BYTE PTR[SI+1]
	ADD DL,'0'
	MOV AH,02H
	INT 21H
	MOV DL, BYTE PTR[SI]
	ADD DL,'0'
	MOV AH,02H
	INT 21H
	POP SI
	POP AX
	POP DX
	MOV WORD PTR CC, AX
	MOV AH, 4CH
	INT 21H
CODES ENDS
	END START
